[build]
  publish = "dist/spa"
  command = "quasar build"
  
[context.production.environment]
  NODE_VERSION = "14"
  NETWORK_CHAIN_ID = "4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11"
  NETWORK_HOST = "telos.caleos.io"
  NETWORK_PORT = "443"
  NETWORK_PROTOCOL = "https"
  NETWORK_EVM_RPC = "https://mainnet.telos.net/evm"
  NETWORK_EVM_ENDPOINT = "https://telos.caleos.io"
  NETWORK_EVM_CONTRACT = "telos.evm"
  NETWORK_EVM_CHAIN_ID = "40"
  NETWORK_EXPLORER = "https://telos.bloks.io"
  HYPERION_ENDPOINT = "https://mainnet.telos.net"
